// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_CarState = NULL;
lv_obj_t * ui_TopLeftPanel = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TopRightPanel = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_BottomLeftPanel = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_BottomRightPanel = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_car = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x17110E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CarState = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_CarState);
    lv_obj_set_width(ui_CarState, 440);
    lv_obj_set_height(ui_CarState, 370);
    lv_obj_set_x(ui_CarState, 1);
    lv_obj_set_y(ui_CarState, -1);
    lv_obj_set_align(ui_CarState, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CarState, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopLeftPanel = lv_obj_create(ui_CarState);
    lv_obj_set_width(ui_TopLeftPanel, 220);
    lv_obj_set_height(ui_TopLeftPanel, 180);
    lv_obj_clear_flag(ui_TopLeftPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopLeftPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopLeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopLeftPanel, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopLeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TopLeftPanel);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label3, "250kpa\n40°C");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_MiSans20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xC71616), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_TopRightPanel = lv_obj_create(ui_CarState);
    lv_obj_set_width(ui_TopRightPanel, 220);
    lv_obj_set_height(ui_TopRightPanel, 180);
    lv_obj_set_align(ui_TopRightPanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_TopRightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopRightPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopRightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TopRightPanel, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopRightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_TopRightPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label1, "250kpa\n40°C");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_MiSans20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomLeftPanel = lv_obj_create(ui_CarState);
    lv_obj_set_width(ui_BottomLeftPanel, 220);
    lv_obj_set_height(ui_BottomLeftPanel, 180);
    lv_obj_set_align(ui_BottomLeftPanel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_BottomLeftPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomLeftPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomLeftPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomLeftPanel, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomLeftPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_BottomLeftPanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label4, "250kpa\n40°C");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_MiSans20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomRightPanel = lv_obj_create(ui_CarState);
    lv_obj_set_width(ui_BottomRightPanel, 220);
    lv_obj_set_height(ui_BottomRightPanel, 180);
    lv_obj_set_align(ui_BottomRightPanel, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_BottomRightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomRightPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomRightPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomRightPanel, lv_color_hex(0xCDCDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomRightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_BottomRightPanel);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label5, "250kpa\n40°C");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_MiSans20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_car = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_car, &ui_img_car_png);
    lv_obj_set_width(ui_car, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_car, LV_SIZE_CONTENT);    /// 1536
    lv_obj_set_align(ui_car, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_car, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_car, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_car, 80);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_CarState = NULL;
    ui_TopLeftPanel = NULL;
    ui_Label3 = NULL;
    ui_TopRightPanel = NULL;
    ui_Label1 = NULL;
    ui_BottomLeftPanel = NULL;
    ui_Label4 = NULL;
    ui_BottomRightPanel = NULL;
    ui_Label5 = NULL;
    ui_car = NULL;

}
