// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_ECO;
extern void ui_event_ECOChange(lv_event_t * e);
extern lv_obj_t * ui_ECOChange;
extern lv_obj_t * ui_WaterTemp;
extern lv_obj_t * ui_TempPoint;
extern lv_obj_t * ui_TempWarning;
extern lv_obj_t * ui_Oil;
extern lv_obj_t * ui_OilPoint;
extern lv_obj_t * ui_KmTable;
extern lv_obj_t * ui_KmPoint;
extern lv_obj_t * ui_ODO;
extern lv_obj_t * ui_TRIP;
extern lv_obj_t * ui_Tachometer;
extern lv_obj_t * ui_TMeterpoint;
extern lv_obj_t * ui_TIME;
extern lv_obj_t * ui_DirectionContainer;
extern lv_obj_t * ui_High_beam;
extern void ui_event_HBChange(lv_event_t * e);
extern lv_obj_t * ui_HBChange;
extern lv_obj_t * ui_Left;
extern lv_obj_t * ui_Right;
extern void ui_event_Engine(lv_event_t * e);
extern lv_obj_t * ui_Engine;
extern void ui_event_EngineChange(lv_event_t * e);
extern lv_obj_t * ui_EngineChange;
extern void ui_event_seat_belt(lv_event_t * e);
extern lv_obj_t * ui_seat_belt;
extern void ui_event_BeltChange(lv_event_t * e);
extern lv_obj_t * ui_BeltChange;
extern void ui_event_Low_engine_oil(lv_event_t * e);
extern lv_obj_t * ui_Low_engine_oil;
extern void ui_event_LowEgOilChange(lv_event_t * e);
extern lv_obj_t * ui_LowEgOilChange;
extern lv_obj_t * ui_Roller1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

