// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_ECO = NULL;
lv_obj_t * ui_ECOChange = NULL;
lv_obj_t * ui_WaterTemp = NULL;
lv_obj_t * ui_TempPoint = NULL;
lv_obj_t * ui_TempWarning = NULL;
lv_obj_t * ui_Oil = NULL;
lv_obj_t * ui_OilPoint = NULL;
lv_obj_t * ui_KmTable = NULL;
lv_obj_t * ui_KmPoint = NULL;
lv_obj_t * ui_ODO = NULL;
lv_obj_t * ui_TRIP = NULL;
lv_obj_t * ui_Tachometer = NULL;
lv_obj_t * ui_TMeterpoint = NULL;
lv_obj_t * ui_TIME = NULL;
lv_obj_t * ui_DirectionContainer = NULL;
lv_obj_t * ui_High_beam = NULL;
lv_obj_t * ui_HBChange = NULL;
lv_obj_t * ui_Left = NULL;
lv_obj_t * ui_Right = NULL;
lv_obj_t * ui_Engine = NULL;
lv_obj_t * ui_EngineChange = NULL;
lv_obj_t * ui_seat_belt = NULL;
lv_obj_t * ui_BeltChange = NULL;
lv_obj_t * ui_Low_engine_oil = NULL;
lv_obj_t * ui_LowEgOilChange = NULL;
lv_obj_t * ui_Roller1 = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 400, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_ECOChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_ECO, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_HBChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_High_beam, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_Engine(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EngineIconBright(e);
    }
}

void ui_event_EngineChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Engine, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_seat_belt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SeatBeltIconBright(e);
    }
}

void ui_event_BeltChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat_belt, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_Low_engine_oil(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LowEngineOilIconBright(e);
    }
}

void ui_event_LowEgOilChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Low_engine_oil, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x17110E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 800);
    lv_obj_set_height(ui_Container1, 480);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ECO = lv_img_create(ui_Container1);
    lv_img_set_src(ui_ECO, &ui_img_1276914373);
    lv_obj_set_width(ui_ECO, LV_SIZE_CONTENT);   /// 162
    lv_obj_set_height(ui_ECO, LV_SIZE_CONTENT);    /// 135
    lv_obj_set_x(ui_ECO, -1);
    lv_obj_set_y(ui_ECO, -95);
    lv_obj_set_align(ui_ECO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ECO, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ECO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ECO, 80);
    lv_obj_set_style_blend_mode(ui_ECO, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ECO, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ECO, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_opa(ui_ECO, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ECOChange = lv_btn_create(ui_ECO);
    lv_obj_set_width(ui_ECOChange, 30);
    lv_obj_set_height(ui_ECOChange, 30);
    lv_obj_set_align(ui_ECOChange, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ECOChange, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ECOChange, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_ECOChange, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ECOChange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterTemp = lv_img_create(ui_Container1);
    lv_img_set_src(ui_WaterTemp, &ui_img_1103686941);
    lv_obj_set_width(ui_WaterTemp, LV_SIZE_CONTENT);   /// 517
    lv_obj_set_height(ui_WaterTemp, LV_SIZE_CONTENT);    /// 517
    lv_obj_set_x(ui_WaterTemp, -314);
    lv_obj_set_y(ui_WaterTemp, 67);
    lv_obj_set_align(ui_WaterTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WaterTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WaterTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WaterTemp, 80);

    ui_TempPoint = lv_img_create(ui_WaterTemp);
    lv_img_set_src(ui_TempPoint, &ui_img_170937940);
    lv_obj_set_width(ui_TempPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempPoint, -68);
    lv_obj_set_y(ui_TempPoint, 16);
    lv_obj_set_align(ui_TempPoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempPoint, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TempPoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_TempPoint, 250, 78);
    lv_img_set_zoom(ui_TempPoint, 80);

    ui_TempWarning = lv_img_create(ui_WaterTemp);
    lv_img_set_src(ui_TempWarning, &ui_img_1357973862);
    lv_obj_set_width(ui_TempWarning, LV_SIZE_CONTENT);   /// 190
    lv_obj_set_height(ui_TempWarning, LV_SIZE_CONTENT);    /// 159
    lv_obj_set_x(ui_TempWarning, -10);
    lv_obj_set_y(ui_TempWarning, 55);
    lv_obj_set_align(ui_TempWarning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempWarning, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TempWarning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_TempWarning, 55);

    ui_Oil = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Oil, &ui_img_1294076047);
    lv_obj_set_width(ui_Oil, LV_SIZE_CONTENT);   /// 517
    lv_obj_set_height(ui_Oil, LV_SIZE_CONTENT);    /// 517
    lv_obj_set_x(ui_Oil, 314);
    lv_obj_set_y(ui_Oil, 67);
    lv_obj_set_align(ui_Oil, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Oil, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Oil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Oil, 80);

    ui_OilPoint = lv_img_create(ui_Oil);
    lv_img_set_src(ui_OilPoint, &ui_img_170937940);
    lv_obj_set_width(ui_OilPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilPoint, -107);
    lv_obj_set_y(ui_OilPoint, 12);
    lv_obj_set_align(ui_OilPoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OilPoint, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OilPoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_OilPoint, 250, 78);
    lv_img_set_angle(ui_OilPoint, 900);
    lv_img_set_zoom(ui_OilPoint, 80);

    ui_KmTable = lv_img_create(ui_Container1);
    lv_img_set_src(ui_KmTable, &ui_img_837434941);
    lv_obj_set_x(ui_KmTable, -150);
    lv_obj_set_y(ui_KmTable, 0);
    lv_obj_set_align(ui_KmTable, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KmTable, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KmTable, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_KmTable, 80);

    ui_KmPoint = lv_img_create(ui_KmTable);
    lv_img_set_src(ui_KmPoint, &ui_img_837427518);
    lv_obj_set_width(ui_KmPoint, LV_SIZE_CONTENT);   /// 455
    lv_obj_set_height(ui_KmPoint, LV_SIZE_CONTENT);    /// 261
    lv_obj_set_x(ui_KmPoint, -134);
    lv_obj_set_y(ui_KmPoint, 69);
    lv_obj_set_align(ui_KmPoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KmPoint, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KmPoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_KmPoint, 355, 66);
    lv_img_set_zoom(ui_KmPoint, 80);

    ui_ODO = lv_label_create(ui_KmTable);
    lv_obj_set_width(ui_ODO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ODO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ODO, -435);
    lv_obj_set_y(ui_ODO, 530);
    lv_obj_set_align(ui_ODO, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ODO, "16863");
    lv_obj_set_style_text_color(ui_ODO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ODO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ODO, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ODO, &ui_font_TIME, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRIP = lv_label_create(ui_KmTable);
    lv_obj_set_width(ui_TRIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRIP, -435);
    lv_obj_set_y(ui_TRIP, 550);
    lv_obj_set_align(ui_TRIP, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_TRIP, "136");
    lv_obj_set_style_text_color(ui_TRIP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TRIP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TRIP, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TRIP, &ui_font_TIME, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tachometer = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Tachometer, &ui_img_837428543);
    lv_obj_set_width(ui_Tachometer, LV_SIZE_CONTENT);   /// 918
    lv_obj_set_height(ui_Tachometer, LV_SIZE_CONTENT);    /// 918
    lv_obj_set_x(ui_Tachometer, 150);
    lv_obj_set_y(ui_Tachometer, 0);
    lv_obj_set_align(ui_Tachometer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tachometer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Tachometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Tachometer, 80);

    ui_TMeterpoint = lv_img_create(ui_Tachometer);
    lv_img_set_src(ui_TMeterpoint, &ui_img_837427518);
    lv_obj_set_width(ui_TMeterpoint, LV_SIZE_CONTENT);   /// 455
    lv_obj_set_height(ui_TMeterpoint, LV_SIZE_CONTENT);    /// 261
    lv_obj_set_x(ui_TMeterpoint, -135);
    lv_obj_set_y(ui_TMeterpoint, 70);
    lv_obj_set_align(ui_TMeterpoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TMeterpoint, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TMeterpoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_TMeterpoint, 355, 66);
    lv_img_set_zoom(ui_TMeterpoint, 80);

    ui_TIME = lv_label_create(ui_Tachometer);
    lv_obj_set_width(ui_TIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TIME, 0);
    lv_obj_set_y(ui_TIME, 77);
    lv_obj_set_align(ui_TIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TIME, "00:00");
    lv_obj_set_style_text_color(ui_TIME, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TIME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TIME, &ui_font_TIME, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DirectionContainer = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_DirectionContainer);
    lv_obj_set_width(ui_DirectionContainer, 209);
    lv_obj_set_height(ui_DirectionContainer, 71);
    lv_obj_set_x(ui_DirectionContainer, 0);
    lv_obj_set_y(ui_DirectionContainer, -139);
    lv_obj_set_align(ui_DirectionContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DirectionContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_High_beam = lv_img_create(ui_DirectionContainer);
    lv_img_set_src(ui_High_beam, &ui_img_1181061765);
    lv_obj_set_width(ui_High_beam, LV_SIZE_CONTENT);   /// 190
    lv_obj_set_height(ui_High_beam, LV_SIZE_CONTENT);    /// 159
    lv_obj_set_align(ui_High_beam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_High_beam, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_High_beam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_High_beam, 80);
    lv_obj_set_style_blend_mode(ui_High_beam, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_High_beam, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_High_beam, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_HBChange = lv_btn_create(ui_High_beam);
    lv_obj_set_width(ui_HBChange, 30);
    lv_obj_set_height(ui_HBChange, 30);
    lv_obj_set_align(ui_HBChange, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HBChange, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HBChange, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_HBChange, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HBChange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left = lv_img_create(ui_DirectionContainer);
    lv_img_set_src(ui_Left, &ui_img_896081354);
    lv_obj_set_width(ui_Left, LV_SIZE_CONTENT);   /// 111
    lv_obj_set_height(ui_Left, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Left, -50);
    lv_obj_set_y(ui_Left, 0);
    lv_obj_set_align(ui_Left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Left, 80);
    lv_obj_set_style_opa(ui_Left, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Right = lv_img_create(ui_DirectionContainer);
    lv_img_set_src(ui_Right, &ui_img_896082379);
    lv_obj_set_width(ui_Right, LV_SIZE_CONTENT);   /// 111
    lv_obj_set_height(ui_Right, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Right, 50);
    lv_obj_set_y(ui_Right, 0);
    lv_obj_set_align(ui_Right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Right, 80);
    lv_obj_set_style_blend_mode(ui_Right, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Right, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Engine = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Engine, &ui_img_869378988);
    lv_obj_set_width(ui_Engine, LV_SIZE_CONTENT);   /// 162
    lv_obj_set_height(ui_Engine, LV_SIZE_CONTENT);    /// 135
    lv_obj_set_x(ui_Engine, -40);
    lv_obj_set_y(ui_Engine, 150);
    lv_obj_set_align(ui_Engine, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Engine, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Engine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Engine, 80);
    lv_obj_set_style_opa(ui_Engine, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Engine, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_EngineChange = lv_btn_create(ui_Engine);
    lv_obj_set_width(ui_EngineChange, 30);
    lv_obj_set_height(ui_EngineChange, 30);
    lv_obj_set_align(ui_EngineChange, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EngineChange, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EngineChange, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_EngineChange, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_EngineChange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seat_belt = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_seat_belt, &ui_img_424233258);
    lv_obj_set_width(ui_seat_belt, LV_SIZE_CONTENT);   /// 190
    lv_obj_set_height(ui_seat_belt, LV_SIZE_CONTENT);    /// 159
    lv_obj_set_x(ui_seat_belt, 0);
    lv_obj_set_y(ui_seat_belt, 90);
    lv_obj_set_align(ui_seat_belt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat_belt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_seat_belt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_seat_belt, 80);
    lv_obj_set_style_opa(ui_seat_belt, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_seat_belt, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BeltChange = lv_btn_create(ui_seat_belt);
    lv_obj_set_width(ui_BeltChange, 30);
    lv_obj_set_height(ui_BeltChange, 30);
    lv_obj_set_align(ui_BeltChange, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BeltChange, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BeltChange, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_BeltChange, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BeltChange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Low_engine_oil = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Low_engine_oil, &ui_img_1357980260);
    lv_obj_set_width(ui_Low_engine_oil, LV_SIZE_CONTENT);   /// 190
    lv_obj_set_height(ui_Low_engine_oil, LV_SIZE_CONTENT);    /// 159
    lv_obj_set_x(ui_Low_engine_oil, 40);
    lv_obj_set_y(ui_Low_engine_oil, 150);
    lv_obj_set_align(ui_Low_engine_oil, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Low_engine_oil, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Low_engine_oil, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Low_engine_oil, 80);
    lv_obj_set_style_opa(ui_Low_engine_oil, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Low_engine_oil, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LowEgOilChange = lv_btn_create(ui_Low_engine_oil);
    lv_obj_set_width(ui_LowEgOilChange, 30);
    lv_obj_set_height(ui_LowEgOilChange, 30);
    lv_obj_set_align(ui_LowEgOilChange, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowEgOilChange, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LowEgOilChange, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_LowEgOilChange, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_LowEgOilChange, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_Roller1, "运动模式\n经济模式\n舒适模式", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller1, 63);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 0);
    lv_obj_set_y(ui_Roller1, 10);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_MiSans18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Roller1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ECOChange, ui_event_ECOChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HBChange, ui_event_HBChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EngineChange, ui_event_EngineChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Engine, ui_event_Engine, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BeltChange, ui_event_BeltChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat_belt, ui_event_seat_belt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LowEgOilChange, ui_event_LowEgOilChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Low_engine_oil, ui_event_Low_engine_oil, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_ECO = NULL;
    ui_ECOChange = NULL;
    ui_WaterTemp = NULL;
    ui_TempPoint = NULL;
    ui_TempWarning = NULL;
    ui_Oil = NULL;
    ui_OilPoint = NULL;
    ui_KmTable = NULL;
    ui_KmPoint = NULL;
    ui_ODO = NULL;
    ui_TRIP = NULL;
    ui_Tachometer = NULL;
    ui_TMeterpoint = NULL;
    ui_TIME = NULL;
    ui_DirectionContainer = NULL;
    ui_High_beam = NULL;
    ui_HBChange = NULL;
    ui_Left = NULL;
    ui_Right = NULL;
    ui_Engine = NULL;
    ui_EngineChange = NULL;
    ui_seat_belt = NULL;
    ui_BeltChange = NULL;
    ui_Low_engine_oil = NULL;
    ui_LowEgOilChange = NULL;
    ui_Roller1 = NULL;

}
