// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_CarState;
extern lv_obj_t * ui_TopLeftPanel;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TopRightPanel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_BottomLeftPanel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_BottomRightPanel;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_car;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

