// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * KmRotate_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * PointRotate2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Waterpoint_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Oilpoint_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Leftflash_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Rightflash_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1276914373);    // assets/组 84.png
LV_IMG_DECLARE(ui_img_1103686941);    // assets/组 8.png
LV_IMG_DECLARE(ui_img_170937940);    // assets/分组 1.png
LV_IMG_DECLARE(ui_img_1357973862);    // assets/组 92.png
LV_IMG_DECLARE(ui_img_1294076047);    // assets/组 13.png
LV_IMG_DECLARE(ui_img_837434941);    // assets/组 31.png
LV_IMG_DECLARE(ui_img_837427518);    // assets/组 30.png
LV_IMG_DECLARE(ui_img_837428543);    // assets/组 37.png
LV_IMG_DECLARE(ui_img_1181061765);    // assets/组 40.png
LV_IMG_DECLARE(ui_img_896081354);    // assets/路径 192.png
LV_IMG_DECLARE(ui_img_896082379);    // assets/路径 193.png
LV_IMG_DECLARE(ui_img_869378988);    // assets/组 76.png
LV_IMG_DECLARE(ui_img_424233258);    // assets/组 100.png
LV_IMG_DECLARE(ui_img_1357980260);    // assets/组 90.png
LV_IMG_DECLARE(ui_img_car_png);    // assets/Car.png

// FONTS
LV_FONT_DECLARE(ui_font_MiSans15);
LV_FONT_DECLARE(ui_font_MiSans18);
LV_FONT_DECLARE(ui_font_MiSans20);
LV_FONT_DECLARE(ui_font_TIME);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
