// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

void EngineIconBright(lv_event_t * e)
{

}

void SeatBeltIconBright(lv_event_t * e)
{

}

void LowEngineOilIconBright(lv_event_t * e)
{

}