// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void EngineIconBright(lv_event_t * e);
void SeatBeltIconBright(lv_event_t * e);
void LowEngineOilIconBright(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
